
dist: trusty
language: node_js
node_js:
  - '9'
sudo: required
addons:
  chrome: stable

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - npm install
  
script:
  - npm run lint
  - npm run build.prod
  - node_modules/.bin/karma start karma.conf.js --single-run


