version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # npm install
      # - command
  pre_build:
    commands:
       - npm install
      # - command
  build:
    commands:
      - npm run build.prod
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - dist/*
    # - location
  #discard-paths: yes
  #base-directory: location