on:
    pull_request:
name: Pull Request
jobs:
    build:
        name: GitHub Action for npm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: 'Build '
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - run: npm ci
            # - run: npm run test
            - run: npm run lint
            - run: npm run build.prod
            
